version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - app
    command: gunicorn -w 2 -b 0.0.0.0:5000 run:app
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app
    command: ["--ssl=0"]
    restart: always

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=user@example.com"
      - "--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./server/letsencrypt:/letsencrypt"  # Pasta para armazenar os certificados
    networks:
      - app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./server/nginx.conf:/etc/nginx/nginx.conf"
      - "./server/letsencrypt:/etc/letsencrypt:ro"
    networks:
      - app
    depends_on:
      - app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`app.test`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      
volumes:
  mysql_data:

networks:
  app:
